ARDUINO_DIR  = /Users/jonathan/Applications/Arduino.app/Contents/Resources/Java
AVR_TOOLS_DIR = $(ARDUINO_DIR)/hardware/tools/avr
ARDMK_DIR    = /Users/jonathan/local/share/Arduino-Makefile/arduino-mk
BOARD_TAG    = uno
MONITOR_PORT = 
ARDUINO_LIBS = 

include $(ARDMK_DIR)/Arduino.mk

